In [70]:
import pandas as pd
import numpy as np
from google.colab import files

#uploaded = files.upload()
df = pd.read_csv('00 Social_Network_Ads.csv')

df.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [71]:
x = df[['Age','EstimatedSalary']]
y = df['Purchased']


print("--- Features (x) ---")
display(x.head())

print("\n--- Target (y) ---")
display(y.head())

--- Features (x) ---

   Age  EstimatedSalary
0   19            19000
1   35            20000
2   26            43000
3   27            57000
4   19            76000

--- Target (y) ---

0    0
1    0
2    0
3    0
4    0
Name: Purchased, dtype: int64

In [72]:
from sklearn.model_selection import train_test_split

In [73]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [74]:
from sklearn.preprocessing import StandardScaler

In [75]:
ss = StandardScaler().set_output(transform='pandas')

In [76]:
x_train_scaled = ss.fit_transform(x_train)
x_test_scaled = ss.transform(x_test)

In [77]:
x_train.describe()

              Age  EstimatedSalary
count  320.000000       320.000000
mean    37.237500     68293.750000
std     10.270625     33878.650655
min     18.000000     15000.000000
25%     29.000000     43000.000000
50%     37.000000     65000.000000
75%     45.000000     85250.000000
max     60.000000    150000.000000

In [78]:
x_train_scaled.describe()

                Age  EstimatedSalary
count  3.200000e+02     3.200000e+02
mean   2.664535e-16     6.938894e-18
std    1.001566e+00     1.001566e+00
min   -1.875994e+00    -1.575541e+00
25%   -8.033008e-01    -7.477678e-01
50%   -2.316042e-02    -9.737426e-02
75%    7.569800e-01     5.012834e-01
max    2.219743e+00     2.415510e+00

In [79]:
from sklearn.linear_model import LogisticRegression

In [80]:
lr = LogisticRegression()

lr_scaled = LogisticRegression()

In [81]:
lr.fit(x_train,y_train)

LogisticRegression()

In [82]:
lr_scaled.fit(x_train_scaled, y_train)

LogisticRegression()

In [83]:
y_pred_unscaled = lr.predict(x_test)

y_pred_scaled = lr_scaled.predict(x_test_scaled)

In [84]:
from sklearn.metrics import accuracy_score

In [85]:
accuracy_unscaled = accuracy_score(y_pred_unscaled,y_test)
accuracy_scaled = accuracy_score(y_pred_scaled,y_test)

In [86]:
print(f"Accuracy on unscaled dataframe = {accuracy_unscaled}.\nAccuracy on scaled dataframe ={accuracy_scaled}. ")

Accuracy on unscaled dataframe = 0.8375.
Accuracy on scaled dataframe =0.8375.